### ISSUE TITLE
a11y: impossible to tab to the region selector

### ISSUE THREAD

**Issue by nathanv** [peterjtracey/timezoneWidget#1] opened 2018-08-20 22:27 UTC
Method to reproduce: load [demo](https://peterjtracey.github.io/timezoneWidget/demo.html). Attempt to tab to the region selector.
Result: impossible to tab to the regional selector.

**Comment by peterjtracey** [comment] 2018-08-22 21:15
This is somewhat by design. If a default region is set, when you tab to the control it puts you in the timezone list. This makes it very easy for those within the default region (for geographically centralized user bases, at least within a continent) to quick get to their timezone. It does need refinement, though, I will either make default region option as false make tabbing into it go to the region select, or have a new option to control the behavior.

**Comment by nathanv** [comment] 2018-08-23 19:46
I appreciate that while this works for sighted users, as per WCAG AA 2.4.3 https://www.w3.org/TR/2008/REC-WCAG20-20081211/#navigation-mechanisms-focus-order a person with a screen reader needs to be able to get through the app properly by tabbing through. See https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-order.html for more rational.

**Comment by peterjtracey** [comment] 2018-10-31 09:47
Ah I see that would be an issue. I can make it optional and include a note that enabling it (I'll make default disabled) may run afoul of AWDA etc. In a lot of cases it does "preserve meaning" to skip the region select, because if people are expected to want the timezone that their machine is currently set to - or one in the same region - being that it auto-selects the timezone (also an option) the user's machine is set to, it will only be the second select that may have meaning. But in many cases such as a person traveling but setting a permanent setting for their home, I agree it is important for them to have awareness of the region select.

Code update coming.

**Comment by peterjtracey** [comment] 2018-11-23 03:22
I have quietly just done away with this feature/bug (featug?) in the latest commits and will be in a new 2.0 release with many major improvements.

**Comment by nathanv** [comment] 2018-11-23 11:19
I will test this morning. Thank you!

**Comment by peterjtracey** [comment] 2018-11-23 18:48
2.0 released just a bit ago.

**Closed as completed by peterjtracey** 2018-11-23 18:48 UTC
